name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services: 
      postgres: 
        image: postgres:15-alpine
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
        ports: 
          - 5432:5432
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Clean frontend dependencies
        working-directory: ./frontend
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Prisma Migrations
        working-directory: ./backend
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }} 
        run: npx prisma migrate deploy

      - name: Add data to DB
        working-directory: ./backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }} 
        run: npm run seed

      - name: Start frontend server
        working-directory: ./frontend
        run: npm run dev &

      - name: Run Jest tests
        working-directory: ./backend
        env:
          CI_TEST: true
          DATABASE_URL: ${{ secrets.DATABASE_URL }} 
          AWS_REGION: ${{ secrets.AWS_REGION }}
          USER_POOL_ID: ${{ secrets.USER_POOL_ID }}
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
          CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
        run: |
          npm test -- src/api/user/user.spec.ts
          npm test -- src/api/pokemon/pokemon.spec.ts

  notify:
    name: Notify Results
    runs-on: ubuntu-latest
    needs: [test]
    
    steps:
      - name: Notify success
        if: ${{ success() }}
        run: echo "All checks passed successfully."

      - name: Notify failure
        if: ${{ failure() }}
        run: echo "One or more checks failed. Please review the reports."
