name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # Cypress specific setup
      - name: Install Cypress
        run: npm install cypress --save-dev

      - name: Run Cypress tests
        run: npx cypress run

  notify:
    name: Notify Results
    runs-on: ubuntu-latest
    needs: [test]
    
    steps:
      - name: Notify success
        if: ${{ success() }}
        run: echo "All checks passed successfully."

      - name: Notify failure
        if: ${{ failure() }}
        run: echo "One or more checks failed. Please review the reports."
